/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List notifications */
    get: operations['NotificationsController_findAll'];
    put?: never;
    /** Create a new notification */
    post: operations['NotificationsController_createNotification'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get notification by ID */
    get: operations['NotificationsController_findOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/queue': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Add pending notifications to queue */
    post: operations['NotificationsController_addNotificationsToQueue'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Get provider confirmation for notifications */
    post: operations['NotificationsController_getProviderConfirmation'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/notifications/redis/cleanup': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cleanup completed and failed Redis jobs */
    post: operations['NotificationsController_cleanupRedisJobs'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List providers */
    get: operations['ProvidersController_findAll'];
    /** Update an existing provider */
    put: operations['ProvidersController_update'];
    /** Create a new provider */
    post: operations['ProvidersController_create'];
    /** Delete a provider */
    delete: operations['ProvidersController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/providers/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get provider by ID */
    get: operations['ProvidersController_findOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/profile': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update own profile */
    put: operations['UsersController_updateProfile'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Change own password */
    post: operations['UsersController_changePassword'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List users */
    get: operations['UsersController_findAll'];
    /** Update an existing user */
    put: operations['UsersController_update'];
    /** Create a new user */
    post: operations['UsersController_create'];
    /** Deactivate a user */
    delete: operations['UsersController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/applications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List applications */
    get: operations['ApplicationsController_findAll'];
    /** Update an existing application */
    put: operations['ApplicationsController_update'];
    /** Create a new application */
    post: operations['ApplicationsController_create'];
    /** Delete an application (soft delete) */
    delete: operations['ApplicationsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/applications/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get application by ID */
    get: operations['ApplicationsController_findOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/provider-chains': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List provider chains */
    get: operations['ProviderChainsController_findAll'];
    /** Update a provider chain */
    put: operations['ProviderChainsController_update'];
    /** Create a new provider chain */
    post: operations['ProviderChainsController_create'];
    /** Delete a provider chain */
    delete: operations['ProviderChainsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/provider-chain-members': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List provider chain members */
    get: operations['ProviderChainMembersController_findAll'];
    put?: never;
    /** Add a member to a provider chain */
    post: operations['ProviderChainMembersController_create'];
    /** Remove a member from a provider chain */
    delete: operations['ProviderChainMembersController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/provider-chain-members/priority-order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update priority order of provider chain members */
    put: operations['ProviderChainMembersController_updatePriorityOrder'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/provider-chain-members/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Restore a deleted provider chain member */
    put: operations['ProviderChainMembersController_restore'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/master-providers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all master providers (read-only catalog) */
    get: operations['MasterProvidersController_findAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api-keys': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all API keys for the organization */
    get: operations['ServerApiKeysController_findAll'];
    put?: never;
    /** Generate a new API key for an application */
    post: operations['ServerApiKeysController_generate'];
    /** Revoke an API key */
    delete: operations['ServerApiKeysController_revoke'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/webhooks': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all webhooks for the organization */
    get: operations['WebhookController_findAll'];
    /** Update a webhook URL */
    put: operations['WebhookController_update'];
    /** Register a new webhook */
    post: operations['WebhookController_create'];
    /** Delete a webhook */
    delete: operations['WebhookController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/archived-notifications': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List archived notifications */
    get: operations['ArchivedNotificationsController_findAll'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/archived-notifications/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get archived notification by ID */
    get: operations['ArchivedNotificationsController_findOne'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/archived-notifications/archive': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Archive completed notifications (scheduler endpoint) */
    post: operations['ArchivedNotificationsController_archiveCompletedNotifications'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/archived-notifications/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete old archived notifications (scheduler endpoint) */
    delete: operations['ArchivedNotificationsController_deleteArchivedNotifications'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login with username and password */
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh access token using refresh token */
    post: operations['AuthController_refresh'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout (invalidate tokens client-side) */
    post: operations['AuthController_logout'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get current user profile */
    get: operations['AuthController_me'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/organizations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all organizations */
    get: operations['OrganizationsController_findAll'];
    /** Update an organization */
    put: operations['OrganizationsController_update'];
    /** Create a new organization */
    post: operations['OrganizationsController_create'];
    /** Delete an organization */
    delete: operations['OrganizationsController_remove'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/dashboard/stats': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get aggregated notification statistics */
    get: operations['DashboardController_getStats'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    NotificationResponseDto: {
      /**
       * @description Notification ID
       * @example 1
       */
      id: number;
      /**
       * @description Provider ID used for delivery
       * @example 1
       */
      provider_id: number;
      /**
       * @description Notification channel: 0=SMTP, 1=Mailgun, 2=AWS SES, etc.
       * @example 0
       */
      channel_type: number;
      /**
       * @description Notification payload data
       * @example {
       *       "to": "user@example.com",
       *       "subject": "Hello",
       *       "body": "World"
       *     }
       */
      data: Record<string, never>;
      /**
       * @description Delivery status: 0=Pending, 1=In Progress, 2=Awaiting Confirmation, 3=Success, 4=Failed
       * @example 0
       */
      delivery_status: number;
      /**
       * @description Provider response result
       * @example {
       *       "messageId": "abc-123"
       *     }
       */
      result?: Record<string, never>;
      /**
       * @description User or API key that created the notification
       * @example admin
       */
      created_by: string;
      /**
       * @description User or API key that last updated the notification
       * @example admin
       */
      updated_by: string;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description Associated application ID
       * @example 1
       */
      application_id: number;
      /**
       * @description Number of delivery retry attempts
       * @example 0
       */
      retry_count: number;
      /**
       * Format: date-time
       * @description Timestamp when notification was sent
       */
      notification_sent_on?: string;
      /**
       * @description Associated provider chain ID
       * @example 1
       */
      provider_chain_id?: number;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    PageInfoDto: {
      /**
       * @description Current page number
       * @example 1
       */
      page: number;
      /**
       * @description Items per page
       * @example 20
       */
      limit: number;
      /**
       * @description Total number of items
       * @example 100
       */
      total_items: number;
      /**
       * @description Total number of pages
       * @example 5
       */
      total_pages: number;
      /**
       * @description Whether a next page exists
       * @example true
       */
      has_next: boolean;
      /**
       * @description Whether a previous page exists
       * @example false
       */
      has_prev: boolean;
    };
    PaginatedResponse: {
      /** @description Array of items */
      items: unknown[][];
      /**
       * @description Self link
       * @example https://host/api/v1/resource?page=1&limit=20
       */
      self: string;
      /** @description First page link */
      first: string;
      /** @description Last page link */
      last: string;
      /** @description Next page link (null if last page) */
      next?: string | null;
      /** @description Previous page link (null if first page) */
      prev?: string | null;
      /** @description Pagination metadata */
      page_info: components['schemas']['PageInfoDto'];
    };
    CreateNotificationDto: {
      dummy: Record<string, never>;
      provider_id?: number;
      provider_chain?: string;
      data: Record<string, never>;
    };
    ProviderResponseDto: {
      /**
       * @description Provider ID
       * @example 1
       */
      provider_id: number;
      /**
       * @description Provider name
       * @example Primary SMTP
       */
      name: string;
      /**
       * @description Notification channel: 0=SMTP, 1=Mailgun, 2=AWS SES, etc.
       * @example 0
       */
      channel_type: number;
      /**
       * @description Whether provider is enabled (0=disabled, 1=enabled)
       * @example 1
       */
      is_enabled: number;
      /**
       * @description Provider-specific configuration (host, port, credentials, etc.)
       * @example {
       *       "host": "smtp.example.com",
       *       "port": 587
       *     }
       */
      configuration: string;
      /**
       * @description Associated application ID
       * @example 1
       */
      application_id: number;
      /**
       * @description Creator user ID
       * @example 1
       */
      user_id: number;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    UpdateProviderInput: {
      /**
       * @description ID of the provider to update
       * @example 1
       */
      provider_id: number;
      /**
       * @description Display name for the provider
       * @example Updated SMTP Provider
       */
      name?: string;
      /**
       * @description Provider-specific configuration object
       * @example {
       *       "host": "smtp.example.com",
       *       "port": 587
       *     }
       */
      configuration?: string;
      /**
       * @description Whether this provider is enabled (0=Disabled, 1=Enabled)
       * @example 1
       */
      is_enabled?: number;
    };
    CreateProviderInput: {
      /**
       * @description ID of the application this provider belongs to
       * @example 1
       */
      application_id: number;
      /**
       * @description Channel type for the provider (1=Email, 2=SMS, 3=WhatsApp Business, 4=Push, 5=Voice, 6=WhatsApp Direct)
       * @example 1
       * @enum {number}
       */
      channel_type: 0 | 1 | 2 | 3 | 4 | 5 | 6;
      /**
       * @description Provider-specific configuration object (e.g., API keys, credentials)
       * @example {
       *       "host": "smtp.example.com",
       *       "port": 587,
       *       "username": "user",
       *       "password": "pass"
       *     }
       */
      configuration: string;
      /**
       * @description Whether this provider is enabled (0=Disabled, 1=Enabled)
       * @example 1
       * @enum {number}
       */
      is_enabled: 0 | 1;
      /**
       * @description Display name for the provider
       * @example SMTP Provider
       */
      name: string;
      /**
       * @description ID of the user creating this provider (derived from JWT in REST endpoints)
       * @example 1
       */
      user_id?: number;
    };
    UserResponseDto: {
      /**
       * @description User ID
       * @example 1
       */
      user_id: number;
      /**
       * @description User email address
       * @example john.doe@example.com
       */
      email: string;
      /**
       * @description First name
       * @example John
       */
      first_name?: string;
      /**
       * @description Last name
       * @example Doe
       */
      last_name?: string;
      /**
       * @description User role: 0=OrgUser, 1=OrgAdmin, 2=SuperAdmin
       * @example 0
       */
      user_role: number;
      /**
       * @description Organization ID
       * @example 1
       */
      organization_id?: number;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    UpdateProfileInput: {
      /**
       * @description First name
       * @example John
       */
      first_name?: string;
      /**
       * @description Last name
       * @example Doe
       */
      last_name?: string;
    };
    ChangePasswordInput: {
      /**
       * @description Current password
       * @example OldP@ssw0rd
       */
      current_password: string;
      /**
       * @description New password (min 6 characters)
       * @example NewP@ssw0rd
       */
      new_password: string;
    };
    CreateUserInput: {
      /**
       * @description User email address (used as login)
       * @example john.doe@example.com
       */
      email: string;
      /**
       * @description User password (min 6 characters)
       * @example password123
       */
      password: string;
      /**
       * @description First name
       * @example John
       */
      first_name?: string;
      /**
       * @description Last name
       * @example Doe
       */
      last_name?: string;
      /**
       * @description User role: 0=OrgUser, 1=OrgAdmin
       * @example 0
       * @enum {number}
       */
      user_role: 0 | 1;
      /**
       * @description Target organization ID (SUPER_ADMIN only, defaults to own org)
       * @example 1
       */
      organization_id?: number;
    };
    UpdateUserInput: {
      /**
       * @description User ID to update
       * @example 1
       */
      user_id: number;
      /**
       * @description New email address
       * @example john.doe@example.com
       */
      email?: string;
      /**
       * @description First name
       * @example John
       */
      first_name?: string;
      /**
       * @description Last name
       * @example Doe
       */
      last_name?: string;
      /**
       * @description New password (min 6 characters)
       * @example newpassword123
       */
      password?: string;
      /**
       * @description User role: 0=OrgUser, 1=OrgAdmin
       * @example 0
       * @enum {number}
       */
      user_role?: 0 | 1;
    };
    ApplicationResponseDto: {
      /**
       * @description Application ID
       * @example 1
       */
      application_id: number;
      /**
       * @description Application name
       * @example My Notification App
       */
      name: string;
      /**
       * @description Owner user ID
       * @example 1
       */
      user_id: number;
      /**
       * @description Organization ID
       * @example 1
       */
      organization_id?: number;
      /**
       * @description Test mode enabled (0=disabled, 1=enabled)
       * @example 0
       */
      test_mode_enabled: number;
      /** @description Whitelisted recipients for test mode */
      whitelist_recipients?: string;
      /**
       * @description Status (1=active, 0=inactive)
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    CreateApplicationInput: {
      /**
       * @description Name of the application
       * @example My Notification App
       */
      name: string;
      /**
       * @description Whether test mode is enabled for this application
       * @example 1
       * @enum {number}
       */
      test_mode_enabled?: 0 | 1;
      /**
       * @description JSON object defining whitelisted recipients for test mode
       * @example {
       *       "email": [
       *         "test@example.com"
       *       ],
       *       "sms": [
       *         "+1234567890"
       *       ]
       *     }
       */
      whitelist_recipients?: string;
    };
    UpdateApplicationInput: {
      /**
       * @description ID of the application to update
       * @example 1
       */
      application_id: number;
      /**
       * @description Updated name of the application
       * @example My Updated App
       */
      name?: string;
      /**
       * @description Whether test mode is enabled for this application
       * @example 1
       * @enum {number}
       */
      test_mode_enabled?: 0 | 1;
      /**
       * @description JSON object defining whitelisted recipients for test mode
       * @example {
       *       "email": [
       *         "test@example.com"
       *       ],
       *       "sms": [
       *         "+1234567890"
       *       ]
       *     }
       */
      whitelist_recipients?: string;
    };
    ProviderChainResponseDto: {
      /**
       * @description Provider chain ID
       * @example 1
       */
      chain_id: number;
      /**
       * @description Chain name
       * @example Email Fallback Chain
       */
      chain_name: string;
      /**
       * @description Associated application ID
       * @example 1
       */
      application_id: number;
      /**
       * @description Provider type identifier
       * @example 1
       */
      provider_type: number;
      /**
       * @description Chain description
       * @example Primary email with fallback
       */
      description?: string;
      /**
       * @description Whether this is the default chain (0=no, 1=yes)
       * @example 0
       */
      is_default: number;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    CreateProviderChainInput: {
      /**
       * @description Name of the provider chain
       * @example Email Fallback Chain
       */
      chain_name: string;
      /**
       * @description ID of the application this chain belongs to
       * @example 1
       */
      application_id: number;
      /**
       * @description Provider type (0=Other, 1=Email, 2=SMS, 3=WhatsApp Business, 4=Push, 5=Voice, 6=WhatsApp Direct)
       * @example 1
       * @enum {number}
       */
      provider_type: 0 | 1 | 2 | 3 | 4 | 5 | 6;
      /**
       * @description Optional description of the provider chain
       * @example Primary email chain with Mailgun fallback to SES
       */
      description?: string;
      /**
       * @description Whether this chain is the default for its provider type (0=No, 1=Yes)
       * @example 1
       * @enum {number}
       */
      is_default?: 0 | 1;
    };
    UpdateProviderChainInput: {
      /**
       * @description ID of the provider chain to update
       * @example 1
       */
      chain_id: number;
      /**
       * @description Updated name of the provider chain
       * @example Updated Email Chain
       */
      chain_name?: string;
      /**
       * @description Updated application ID
       * @example 2
       */
      application_id?: number;
      /**
       * @description Updated provider type (0=Other, 1=Email, 2=SMS, 3=WhatsApp Business, 4=Push, 5=Voice, 6=WhatsApp Direct)
       * @example 1
       * @enum {number}
       */
      provider_type?: 0 | 1 | 2 | 3 | 4 | 5 | 6;
      /**
       * @description Updated description of the provider chain
       * @example Updated fallback chain description
       */
      description?: string;
      /**
       * @description Whether this chain is the default for its provider type (0=No, 1=Yes)
       * @example 1
       * @enum {number}
       */
      is_default?: 0 | 1;
    };
    ProviderChainMemberResponseDto: {
      /**
       * @description Chain member ID
       * @example 1
       */
      id: number;
      /**
       * @description Parent chain ID
       * @example 1
       */
      chain_id: number;
      /**
       * @description Provider ID
       * @example 1
       */
      provider_id: number;
      /**
       * @description Priority order in the fallback chain (lower = higher priority)
       * @example 1
       */
      priority_order: number;
      /**
       * @description Whether member is active (0=inactive, 1=active)
       * @example 1
       */
      is_active: number;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    CreateProviderChainMemberInput: {
      /**
       * @description ID of the provider chain to add the member to
       * @example 1
       */
      chain_id: number;
      /**
       * @description ID of the provider to add as a chain member
       * @example 3
       */
      provider_id: number;
      /**
       * @description Whether the chain member is active (0=Inactive, 1=Active)
       * @example 1
       * @enum {number}
       */
      is_active: 0 | 1;
    };
    UpdateProviderPriorityOrderInput: {
      /**
       * @description ID of the provider chain to reorder
       * @example 1
       */
      chain_id: number;
      /**
       * @description Ordered array of provider IDs representing the new priority order (first = highest priority)
       * @example [
       *       3,
       *       1,
       *       2
       *     ]
       */
      new_provider_priority_order: number[];
    };
    DeleteProviderChainMemberInput: {
      /**
       * @description ID of the provider chain
       * @example 1
       */
      chain_id: number;
      /**
       * @description ID of the provider to remove from the chain
       * @example 3
       */
      provider_id: number;
    };
    MasterProviderResponseDto: {
      /**
       * @description Master provider ID
       * @example 1
       */
      master_id: number;
      /**
       * @description Provider name
       * @example SMTP
       */
      name: string;
      /**
       * @description Provider type identifier
       * @example 1
       */
      provider_type: number;
      /**
       * @description JSON schema defining the provider configuration fields
       * @example {
       *       "host": "string",
       *       "port": "number",
       *       "username": "string",
       *       "password": "string"
       *     }
       */
      configuration: string;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    ServerApiKeyResponseDto: {
      /**
       * @description Server API key ID
       * @example 1
       */
      api_key_id: number;
      /**
       * @description Masked display version of the API key
       * @example sk-****abcd
       */
      masked_api_key: string;
      /**
       * @description Associated application ID
       * @example 1
       */
      application_id: number;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    WebhookResponseDto: {
      /**
       * @description Webhook ID
       * @example 1
       */
      id: number;
      /**
       * @description Associated provider ID
       * @example 1
       */
      provider_id: number;
      /**
       * @description Webhook callback URL
       * @example https://example.com/webhooks/notifications
       */
      webhook_url: string;
      /**
       * @description Whether the webhook URL has been verified
       * @example 0
       */
      is_verified: number;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    CreateWebhookInput: {
      /**
       * @description ID of the provider to associate the webhook with
       * @example 1
       */
      provider_id: number;
      /**
       * @description URL that will receive webhook notifications
       * @example https://example.com/webhooks/notifications
       */
      webhook_url: string;
    };
    UpdateWebhookInput: {
      /**
       * @description ID of the webhook to update
       * @example 1
       */
      id: number;
      /**
       * @description New webhook callback URL
       * @example https://example.com/webhooks/notifications
       */
      webhook_url: string;
    };
    ArchivedNotificationResponseDto: {
      /**
       * @description Archived notification record ID
       * @example 1
       */
      id: number;
      /**
       * @description Original notification ID
       * @example 42
       */
      notification_id: number;
      /**
       * @description Provider ID used for delivery
       * @example 1
       */
      provider_id: number;
      /**
       * @description Notification channel: 0=SMTP, 1=Mailgun, 2=AWS SES, etc.
       * @example 0
       */
      channel_type: number;
      /**
       * @description Notification payload data
       * @example {
       *       "to": "user@example.com",
       *       "subject": "Hello",
       *       "body": "World"
       *     }
       */
      data: Record<string, never>;
      /**
       * @description Delivery status: 0=Pending, 1=In Progress, 2=Awaiting Confirmation, 3=Success, 4=Failed
       * @example 3
       */
      delivery_status: number;
      /**
       * @description Provider response result
       * @example {
       *       "messageId": "abc-123"
       *     }
       */
      result?: Record<string, never>;
      /**
       * @description User or API key that created the notification
       * @example admin
       */
      created_by: string;
      /**
       * @description User or API key that last updated the notification
       * @example admin
       */
      updated_by: string;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description Associated application ID
       * @example 1
       */
      application_id: number;
      /**
       * @description Number of delivery retry attempts
       * @example 0
       */
      retry_count: number;
      /**
       * Format: date-time
       * @description Timestamp when notification was sent
       */
      notification_sent_on?: string;
      /**
       * @description Associated provider chain ID
       * @example 1
       */
      provider_chain_id?: number;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    LoginUserInput: {
      /**
       * @description Email for authentication
       * @example admin@osmox.dev
       */
      email: string;
      /**
       * @description Password for authentication
       * @example P@ssw0rd123
       */
      password: string;
    };
    AuthUserData: {
      /** @example 1 */
      user_id: number;
      /** @example admin@osmox.dev */
      email: string;
      /** @example Admin */
      first_name?: string;
      /** @example User */
      last_name?: string;
      /**
       * @description 0=OrgUser, 1=OrgAdmin, 2=SuperAdmin
       * @example 1
       */
      role: number;
      /** @example 1 */
      organization_id: number;
    };
    AuthResponseDto: {
      /**
       * @description JWT access token
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      access_token: string;
      /**
       * @description JWT refresh token (longer expiration)
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      refresh_token: string;
      /** @description Authenticated user data */
      user: components['schemas']['AuthUserData'];
      /**
       * @description Access token expiration time in seconds
       * @example 604800
       */
      expires_in: number;
    };
    RefreshTokenDto: {
      /**
       * @description Refresh token received from login or previous refresh
       * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
       */
      refresh_token: string;
    };
    OrganizationResponseDto: {
      /**
       * @description Organization ID
       * @example 1
       */
      organization_id: number;
      /**
       * @description Organization name
       * @example Acme Corp
       */
      name: string;
      /**
       * @description URL-friendly slug
       * @example acme-corp
       */
      slug: string;
      /**
       * @description Status: 1=Active, 0=Inactive
       * @example 1
       */
      status: number;
      /**
       * @description ID of user who created this record
       * @example 1
       */
      created_by?: number | null;
      /**
       * @description ID of user who last updated this record
       * @example 1
       */
      updated_by?: number | null;
      /**
       * Format: date-time
       * @description Creation timestamp
       */
      created_on: string;
      /**
       * Format: date-time
       * @description Last update timestamp
       */
      updated_on: string;
    };
    CreateOrganizationInput: {
      /**
       * @description Organization name
       * @example Acme Corp
       */
      name: string;
      /**
       * @description URL-friendly slug (lowercase, alphanumeric, hyphens only)
       * @example acme-corp
       */
      slug: string;
    };
    UpdateOrganizationInput: {
      /**
       * @description ID of the organization to update
       * @example 1
       */
      organization_id: number;
      /**
       * @description Organization display name
       * @example Acme Corp
       */
      name?: string;
      /**
       * @description URL-friendly slug (lowercase, alphanumeric, hyphens)
       * @example acme-corp
       */
      slug?: string;
    };
    DashboardStatsResponseDto: {
      /**
       * @description Total number of active applications
       * @example 5
       */
      total_applications: number;
      /**
       * @description Total number of active providers
       * @example 12
       */
      total_providers: number;
      /**
       * @description Total number of notifications
       * @example 1000
       */
      total_notifications: number;
      /**
       * @description Number of successfully delivered notifications
       * @example 850
       */
      successful_notifications: number;
      /**
       * @description Number of failed notifications
       * @example 50
       */
      failed_notifications: number;
      /**
       * @description Number of pending notifications
       * @example 100
       */
      pending_notifications: number;
      /**
       * @description Success rate as a percentage (0-100)
       * @example 85
       */
      success_rate: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  NotificationsController_findAll: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Field to sort by (snake_case, e.g. created_on) */
        sort?: string;
        /** @description Sort order */
        order?: 'asc' | 'desc';
        /** @description Search text (searches across data, result, and createdBy fields) */
        search?: string;
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
        /** @description Filter by channel type */
        channel_type?: number;
        /** @description Filter by delivery status */
        delivery_status?: number;
        /** @description Filter by application */
        application_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of notifications */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_createNotification: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateNotificationDto'];
      };
    };
    responses: {
      /** @description Notification created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_findOne: {
    parameters: {
      query?: {
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notification details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['NotificationResponseDto'];
        };
      };
      /** @description Notification not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_addNotificationsToQueue: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Notifications queued successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_getProviderConfirmation: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Provider confirmation processed */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  NotificationsController_cleanupRedisJobs: {
    parameters: {
      query?: {
        gracePeriod?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Redis cleanup completed */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProvidersController_findAll: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Field to sort by (snake_case, e.g. created_on) */
        sort?: string;
        /** @description Sort order */
        order?: 'asc' | 'desc';
        /** @description Search text (searches across data, result, and createdBy fields) */
        search?: string;
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of providers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProvidersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProviderInput'];
      };
    };
    responses: {
      /** @description Provider updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProvidersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProviderInput'];
      };
    };
    responses: {
      /** @description Provider created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProvidersController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Provider deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProvidersController_findOne: {
    parameters: {
      query?: {
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Provider details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderResponseDto'];
        };
      };
      /** @description Provider not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_updateProfile: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProfileInput'];
      };
    };
    responses: {
      /** @description Profile updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_changePassword: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordInput'];
      };
    };
    responses: {
      /** @description Password changed successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Current password is incorrect */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_findAll: {
    parameters: {
      query?: {
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of users in the organization */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserInput'];
      };
    };
    responses: {
      /** @description User updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateUserInput'];
      };
    };
    responses: {
      /** @description User created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  UsersController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User deactivated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_findAll: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Field to sort by (snake_case, e.g. created_on) */
        sort?: string;
        /** @description Sort order */
        order?: 'asc' | 'desc';
        /** @description Search text (searches across data, result, and createdBy fields) */
        search?: string;
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of applications */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateApplicationInput'];
      };
    };
    responses: {
      /** @description Application updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateApplicationInput'];
      };
    };
    responses: {
      /** @description Application created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Application deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ApplicationsController_findOne: {
    parameters: {
      query?: {
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Application details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ApplicationResponseDto'];
        };
      };
      /** @description Application not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainsController_findAll: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Field to sort by (snake_case, e.g. created_on) */
        sort?: string;
        /** @description Sort order */
        order?: 'asc' | 'desc';
        /** @description Search text (searches across data, result, and createdBy fields) */
        search?: string;
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of provider chains */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProviderChainInput'];
      };
    };
    responses: {
      /** @description Provider chain updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderChainResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProviderChainInput'];
      };
    };
    responses: {
      /** @description Provider chain created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderChainResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Provider chain deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainMembersController_findAll: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Field to sort by (snake_case, e.g. created_on) */
        sort?: string;
        /** @description Sort order */
        order?: 'asc' | 'desc';
        /** @description Search text (searches across data, result, and createdBy fields) */
        search?: string;
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
        /** @description Filter members by provider chain ID */
        chain_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of provider chain members */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainMembersController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateProviderChainMemberInput'];
      };
    };
    responses: {
      /** @description Provider chain member created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderChainMemberResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainMembersController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteProviderChainMemberInput'];
      };
    };
    responses: {
      /** @description Provider chain member deleted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderChainMemberResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainMembersController_updatePriorityOrder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateProviderPriorityOrderInput'];
      };
    };
    responses: {
      /** @description Priority order updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderChainMemberResponseDto'][];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ProviderChainMembersController_restore: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteProviderChainMemberInput'];
      };
    };
    responses: {
      /** @description Provider chain member restored successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProviderChainMemberResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  MasterProvidersController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all master providers */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MasterProviderResponseDto'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ServerApiKeysController_findAll: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Field to sort by (snake_case, e.g. created_on) */
        sort?: string;
        /** @description Sort order */
        order?: 'asc' | 'desc';
        /** @description Search text (searches across data, result, and createdBy fields) */
        search?: string;
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of API keys */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ServerApiKeysController_generate: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API key generated successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ServerApiKeysController_revoke: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API key revoked */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WebhookController_findAll: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Field to sort by (snake_case, e.g. created_on) */
        sort?: string;
        /** @description Sort order */
        order?: 'asc' | 'desc';
        /** @description Search text (searches across data, result, and createdBy fields) */
        search?: string;
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of webhooks */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WebhookController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateWebhookInput'];
      };
    };
    responses: {
      /** @description Webhook updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WebhookResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WebhookController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateWebhookInput'];
      };
    };
    responses: {
      /** @description Webhook registered successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WebhookResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  WebhookController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Webhook deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArchivedNotificationsController_findAll: {
    parameters: {
      query?: {
        /** @description Page number (1-based) */
        page?: number;
        /** @description Items per page */
        limit?: number;
        /** @description Field to sort by (snake_case, e.g. created_on) */
        sort?: string;
        /** @description Sort order */
        order?: 'asc' | 'desc';
        /** @description Search text (searches across data, result, and createdBy fields) */
        search?: string;
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
        /** @description Filter by channel type */
        channel_type?: number;
        /** @description Filter by delivery status */
        delivery_status?: number;
        /** @description Filter by application */
        application_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Paginated list of archived notifications */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PaginatedResponse'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArchivedNotificationsController_findOne: {
    parameters: {
      query?: {
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Archived notification details */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ArchivedNotificationResponseDto'];
        };
      };
      /** @description Archived notification not found */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArchivedNotificationsController_archiveCompletedNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Completed notifications archived */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  ArchivedNotificationsController_deleteArchivedNotifications: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Old archived notifications deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginUserInput'];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_refresh: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RefreshTokenDto'];
      };
    };
    responses: {
      /** @description Token refreshed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponseDto'];
        };
      };
      /** @description Invalid or expired refresh token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_logout: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Logged out successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  AuthController_me: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Current user profile */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrganizationsController_findAll: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description List of all organizations */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationResponseDto'][];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Super Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrganizationsController_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateOrganizationInput'];
      };
    };
    responses: {
      /** @description Organization updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Super Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrganizationsController_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateOrganizationInput'];
      };
    };
    responses: {
      /** @description Organization created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrganizationResponseDto'];
        };
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Super Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  OrganizationsController_remove: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Organization deleted */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Bad request */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Forbidden - Super Admin only */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  DashboardController_getStats: {
    parameters: {
      query?: {
        /** @description Target org (SUPER_ADMIN only) */
        organization_id?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Dashboard statistics */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardStatsResponseDto'];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
