#!/usr/bin/env node
// Writes src/app/core/constants/app-version.ts from package.json's `version`.
//
// Run from the prestart / prebuild:prod / pretest:ci hooks, so the constant can
// never drift from package.json after a release bump. The generated file is
// committed so a fresh clone type-checks and builds without running this first.
//
// Why generate instead of importing package.json directly: `resolveJsonModule`
// inlines the whole manifest into the bundle, publishing every dependency name
// and version in the served JavaScript. This ships the version string alone.
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const target = join(root, 'src/app/core/constants/app-version.ts');

const contents = `// Generated by scripts/generate-version.mjs from package.json — do not edit by hand.
export const APP_VERSION = '${version}';
`;

if (!existsSync(target) || readFileSync(target, 'utf8') !== contents) {
  writeFileSync(target, contents);
  console.log(`generate-version: app-version.ts -> ${version}`);
}
