services:
  osmox-portal:
    build:
      context: .
      dockerfile: Dockerfile
    image: osmox-portal-${COMPOSE_PROJECT_NAME}
    restart: unless-stopped
    ports:
      - '127.0.0.1:${SERVER_PORT}:80'
