services:
  osmox-portal:
    build:
      context: .
      args:
        PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      dockerfile: Dockerfile
    image: osmox-portal-${COMPOSE_PROJECT_NAME}
    ports:
      - '127.0.0.1:${SERVER_PORT}:80'
