version: '3'
services:
  osmox-api:
    container_name: osmox-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - mariadb
      - redis
    environment:
      NODE_ENV: production

  mariadb:
    container_name: osmox-mariadb
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - '127.0.0.1:${MARIADB_DOCKER_PORT}:3306'
    volumes:
      - osmox-db:/var/lib/mysql

  redis:
    container_name: osmox-redis
    image: redis:latest
    restart: always
    ports:
      - '127.0.0.1:${REDIS_DOCKER_PORT}:6379'

volumes:
  osmox-db: ~
